# Prometheus configuration for EstFor Asset Collection System

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # EstFor App metrics
  - job_name: "estfor-app"
    static_configs:
      - targets: ["app:8000"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # EstFor Worker metrics
  - job_name: "estfor-worker"
    static_configs:
      - targets: ["worker:8000"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # Firestore emulator metrics (if available)
  - job_name: "firestore"
    static_configs:
      - targets: ["firestore:8080"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s

  # Node exporter (if available)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
# Recording rules for common queries
# (Defined in global rule_files section above)
