name: EstFor CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - "estfor/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "estfor/**"

env:
  PROJECT_DIR: estfor
  DOCKER_IMAGE: estfor-app
  DOCKER_TAG: ${{ github.sha }}

jobs:
  # Quick Development Tests (Feature Branches)
  quick-test:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          # Install MongoDB shell for health checks
          wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run linting
        run: |
          black --check --diff .
          isort --check-only --diff .
          flake8 .

      - name: Run type checking
        run: mypy app/

      - name: Run unit tests
        run: |
          pytest tests/test_unit.py tests/test_game_constants.py -v --cov=app --cov-report=xml --cov-report=term-missing --cov-fail-under=60 --disable-warnings

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ${{ env.PROJECT_DIR }}/coverage.xml
          flags: estfor-unit
          name: estfor-unit-coverage

  # Comprehensive Testing (Main Branch)
  comprehensive-test:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    services:
      mongodb:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: estfor_test
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 30s

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          # Install MongoDB shell for health checks
          wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Wait for services to be ready
        run: |
          # Wait for MongoDB
          timeout 60 bash -c 'until mongosh mongodb://admin:password@localhost:27017/estfor_test?authSource=admin --eval "db.runCommand({ping: 1})" --quiet; do sleep 2; done'
          # Wait for Redis
          timeout 30 bash -c 'until redis-cli -h localhost -p 6379 ping | grep -q PONG; do sleep 2; done'
          echo "Services are ready"

      - name: Run all tests
        env:
          MONGODB_URI: mongodb://admin:password@localhost:27017/estfor_test?authSource=admin
          MONGODB_DATABASE: estfor_test
          MONGODB_COLLECTION: all_assets_test
          REDIS_URL: redis://localhost:6379/0
          CELERY_BROKER_URL: redis://localhost:6379/1
          CELERY_RESULT_BACKEND: redis://localhost:6379/2
          ENVIRONMENT: test
          LOG_LEVEL: DEBUG
        run: |
          pytest tests/ -v --cov=app --cov-report=xml --cov-report=term-missing --cov-report=html --cov-fail-under=75

      - name: Run security scan
        run: |
          bandit -r app/ -f json -o bandit-report.json || true
          safety check --json --output safety-report.json || true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ${{ env.PROJECT_DIR }}/coverage.xml
          flags: estfor-comprehensive
          name: estfor-comprehensive-coverage

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            ${{ env.PROJECT_DIR }}/bandit-report.json
            ${{ env.PROJECT_DIR }}/safety-report.json

  # Docker Build and Security Scan
  docker-build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: comprehensive-test
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
          docker build -t ${{ env.DOCKER_IMAGE }}:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

      - name: Save Docker image
        run: |
          docker save ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} -o /tmp/docker-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/docker-image.tar

  # Performance Testing
  performance-test:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: docker-build
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load -i /tmp/docker-image.tar

      - name: Start application services
        run: |
          docker-compose up -d
          echo "Waiting for services to be ready..."
          
      - name: Wait for application to be ready
        run: |
          # Wait up to 2 minutes for the application to be ready
          timeout 120 bash -c 'until curl -f http://localhost:8000/health >/dev/null 2>&1; do
            echo "Waiting for application to be ready..."
            sleep 5
          done'
          echo "Application is ready for load testing"

      - name: Run k6 load test
        run: |
          k6 run k6/load-test.js --out json=results.json
        env:
          BASE_URL: http://localhost:8000
          SCENARIO: load

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: ${{ env.PROJECT_DIR }}/results.json

      - name: Cleanup
        if: always()
        run: |
          docker-compose down -v
          docker system prune -f

  # Production Deployment
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [comprehensive-test, docker-build, performance-test]
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load -i /tmp/docker-image.tar

      - name: Deploy to production
        run: |
          echo "Deploying EstFor Asset Collection System to production..."
          echo "Docker image loaded: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}"
          # Add your production deployment commands here
          # Example: docker-compose -f docker-compose.prod.yml up -d

      - name: Health check
        run: |
          echo "Running post-deployment health checks..."
          # Add health check commands here
          # Example: curl -f http://your-app-url/health

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ EstFor production deployment successful!"
          echo "Version: ${{ env.DOCKER_TAG }}"
          echo "Timestamp: $(date -u)"
          # Add notification logic here (Slack, email, etc.)

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ EstFor production deployment failed!"
          echo "Version: ${{ env.DOCKER_TAG }}"
          echo "Timestamp: $(date -u)"
          # Add failure notification logic here
