name: Quick Development Test

on:
  push:
    branches:
      - feature
    paths:
      - "estfor/app/**"
      - "estfor/tests/**"
      - "estfor/requirements*.txt"

jobs:
  quick-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: estfor

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Quick syntax check
        run: |
          python -m py_compile app/main.py
          python -m py_compile app/config.py
          echo "✅ Syntax check passed"

      - name: Run basic tests
        run: |
          pytest tests/test_unit.py -v

      - name: Quick Docker test
        run: |
          docker build -t estfor:quick .
          echo "✅ Docker build successful"
