name: Whispered Video CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - "whispered_video/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "whispered_video/**"

env:
  PROJECT_DIR: whispered_video/app
  DOCKER_IMAGE: whispered-video-app
  DOCKER_TAG: ${{ github.sha }}

jobs:
  # Quick Development Tests (Feature Branches)
  quick-test:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          flake8 . --max-line-length=88 --extend-ignore=E203,W503
          python -m py_compile *.py

      - name: Run basic tests
        run: |
          python test_app.py
          python test_output_formats.py

      - name: Test Docker build
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .

  # Comprehensive Testing (Main Branch)
  comprehensive-test:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run all tests
        run: |
          python test_app.py
          python test_output_formats.py

      - name: Run security scan
        run: |
          bandit -r . -f json -o bandit-report.json || true
          safety check --json --output safety-report.json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: whispered-video-security-reports
          path: |
            ${{ env.PROJECT_DIR }}/bandit-report.json
            ${{ env.PROJECT_DIR }}/safety-report.json

  # Docker Build and Security Scan
  docker-build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: comprehensive-test
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
          docker build -t ${{ env.DOCKER_IMAGE }}:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

      - name: Save Docker image
        run: |
          docker save ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} -o /tmp/docker-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: whispered-video-docker-image
          path: /tmp/docker-image.tar

  # Integration Testing
  integration-test:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: docker-build
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: whispered-video-docker-image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load -i /tmp/docker-image.tar

      - name: Test Docker container
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} --help

      - name: Test with sample video
        run: |
          # Create a test video file (if needed)
          # docker run --rm -v $(pwd):/app ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} --input test.mp4

  # Production Deployment
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [comprehensive-test, docker-build, integration-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: whispered-video-docker-image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load -i /tmp/docker-image.tar

      - name: Deploy to production
        run: |
          echo "Deploying Whispered Video to production..."
          # Add your production deployment commands here
          # Example: docker-compose -f docker-compose.prod.yml up -d

      - name: Health check
        run: |
          echo "Running health checks..."
          # Add health check commands here

      - name: Notify deployment success
        if: success()
        run: |
          echo "Whispered Video production deployment successful!"
          # Add notification logic here (Slack, email, etc.)

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "Whispered Video production deployment failed!"
          # Add failure notification logic here
